version: '3'
services:
  server_one:
    build: httpserver1
    ports:
      - "3000:3000"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - REPEATER_HOST=server_two
      - REPEATER_PORT=3001
    networks:
      - reselnet
  server_two:
    build: httpserver2
    ports:
      - "3001:3001"
    environment:
      - JAEGER_AGENT_HOST=jaeger
    networks:
      - reselnet
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - reselnet
networks:
  reselnet:
